name: CI/CD Docker3

on:
  push:
    branches: [ main ]

env:
  VERSION: ${{ github.sha }}
  NAME: devops

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean bootJar

      - name: Docker image build
        run: docker build -t ${{ secrets.USERNAME }}/devops:${{ env.VERSION }} .

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Docker Hub push
        run: docker push ${{ secrets.USERNAME }}/devops:${{ env.VERSION }}

  deploy:
    needs: build-docker-image
    runs-on: [self-hosted, label-go2]
    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Docker run
        run: |
          sudo docker stop devops-app1_1 && sudo docker rm devops-app1_1
          sudo docker run -d --network devops_my_bridge_network --name devops-app1_1 --restart always ${{ secrets.USERNAME }}/devops:${{ env.VERSION }}
          sudo docker stop devops-app2_1 && sudo docker rm devops-app2_1
          sudo docker run -d --network devops_my_bridge_network --name devops-app2_1 --restart always ${{ secrets.USERNAME }}/devops:${{ env.VERSION }}
          sudo docker image prune -af
